### ISSUE TITLE
demo is not work

### ISSUE THREAD

**Issue by qingtong234** [ajainarayanan/redux-undoredo#1]
I see the demo from http://react-dag-app.surge.sh/complexdag, when i move the node first time, undo works, then i move another node, this time undo not work

**Comment by ajainarayanan** [comment]
Hi @qingtong234 . Can you provide a sequence of steps to reproduce the error? Are there any errors you seeing in debugger console (in chrome or firefox)?

**Comment by qingtong234** [comment]
@ajainarayanan, this is the step3 that not work:
1. move the node position
2. click undo button, this works
3. move node position again
4. this time undo not work

The fact is once I clicked the undo action, then whatever action I made can not be undo

**Comment by ajainarayanan** [comment]
@qingtong234 Thanks for the steps! I have found the bug and I have fixed the issue. Can you try the link you posted again?
